### ISSUE TITLE
authentication error with mariadb

### ISSUE THREAD

**Issue by pedro-nonfree** [nextcloud/user_sql#36]
I suspect that this plugin is not compatible with mariadb (which is the default mysql in debian 9 stable)

Looks like I configured succesfully a connection to a wordpress with mariadb using nextcloud

this is what says `nextcloud.log` when I try to login with a wordpress user

```
{
	"reqId": "RQZScPRis9H9T2pwoFkh",
	"level": 3,
	"time": "2018-05-31T22:19:17+00:00",
	"remoteAddr": "<masked>",
	"user": "admin",
	"app": "index",
	"method": "GET",
	"url": "/index.php/apps/files/",
	"message": "Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\SyntaxErrorException\",\"Message\":\"An exception occurred while executing 'SELECT  FROM wp_users WHERE user_login = :uid' with params [\\\"admin\\\"]:\\n\\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'FROM wp_users WHERE user_login = 'admin'' at line 1\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/html\\/nextcloud\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\/var\\/www\\/html\\/nextcloud\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Statement.php(177): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT  FROM wp...', Array)\\n#2 \\/var\\/www\\/html\\/nextcloud\\/apps\\/user_sql\\/lib\\/helper.php(218): Doctrine\\\\DBAL\\\\Statement->execute()\\n#3 \\/var\\/www\\/html\\/nextcloud\\/apps\\/user_sql\\/lib\\/user_sql.php(594): OCA\\\\user_sql\\\\lib\\\\Helper->runQuery('getDisplayName', Array)\\n#4 \\/var\\/www\\/html\\/nextcloud\\/lib\\/private\\/User\\/User.php(120): OCA\\\\user_sql\\\\OC_USER_SQL->getDisplayName('admin')\\n#5 \\/var\\/www\\/html\\/nextcloud\\/lib\\/private\\/legacy\\/helper.php(603): OC\\\\User\\\\User->getDisplayName()\\n#6 \\/var\\/www\\/html\\/nextcloud\\/apps\\/files\\/lib\\/Controller\\/ViewController.php(131): OC_Helper::getStorageInfo('\\/', Object(OC\\\\Files\\\\FileInfo))\\n#7 \\/var\\/www\\/html\\/nextcloud\\/apps\\/files\\/lib\\/Controller\\/ViewController.php(160): OCA\\\\Files\\\\Controller\\\\ViewController->getStorageInfo()\\n#8 [internal function]: OCA\\\\Files\\\\Controller\\\\ViewController->index('', '', NULL, false)\\n#9 \\/var\\/www\\/html\\/nextcloud\\/lib\\/private\\/AppFramework\\/Http\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#10 \\/var\\/www\\/html\\/nextcloud\\/lib\\/private\\/AppFramework\\/Http\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#11 \\/var\\/www\\/html\\/nextcloud\\/lib\\/private\\/AppFramework\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#12 \\/var\\/www\\/html\\/nextcloud\\/lib\\/private\\/AppFramework\\/Routing\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#13 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#14 \\/var\\/www\\/html\\/nextcloud\\/lib\\/private\\/Route\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#15 \\/var\\/www\\/html\\/nextcloud\\/lib\\/base.php(999): OC\\\\Route\\\\Router->match('\\/apps\\/files\\/')\\n#16 \\/var\\/www\\/html\\/nextcloud\\/index.php(37): OC::handleRequest()\\n#17 {main}\",\"File\":\"\\/var\\/www\\/html\\/nextcloud\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Driver\\/AbstractMySQLDriver.php\",\"Line\":90}",
	"userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36",
	"version": "13.0.2.1"
}
```

**Comment by mlojewski-me** [comment]
Your configuration is missing some columns. Check if you set column name for username.

**Comment by pedro-nonfree** [comment]
You are right, I was missing `Real Name Column` to `display_name` and `User Active Column` to `user_status`. Now it works! Thank you very much!

I'm going to pull request your README.md for the wordpress case
